# Simple deployment used to deploy and manage the app in illion13/k8s:1.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: web
spec:
  replicas: 6
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: hello-pod
        image: illion13/k8s:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
