apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  workflowSpec:
    workflowTemplateRef:
      name: hellocontrolplane $ ^C
controlplane $ cat hello-workflowtemplate.yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: docker/whalesay
